### ISSUE TITLE
Add support for the opposite behavior (disable HDR once an application launches)

### ISSUE THREAD

**Issue by flowerdealer** [Codectory/AutoHDR#21]
Oculus and many remote desktop applications don't work properly when hdr mode is enabled, so I want to disable hdr when those applications launch. Would it be possible to do it via this app?

**Comment by Codectory** [comment]
The only way this will work at the moment is to disable hdr in Windows and
add all apps you want hdr to be enabled in the AutoHDR app

flowerdealer ***@***.***> schrieb am Mi. 14. Apr. 2021 um
21:20:

**Comment by flowerdealer** [comment]
I've managed to compile a crappy version that inverts the behaviour for myself, please consider implementing it for some future version. I would love to contribute but my c# skills are crap.

**Comment by flowerdealer** [comment]
Example usage: Using to disable while using Moonlight streaming, Virtual desktop streaming, SteamVR, Oculus Client. This implementation is the perfect solution.

**Comment by Codectory** [comment]
You can do this with profiles now.

**Comment by flowerdealer** [comment]
Hi, this doesn't seem to be working. I've set my Application Open status to All displays [HDR no], and nothing happens. It

**Comment by Codectory** [comment]
You need to check set hdr and leave activate hdr unchecked

flowerdealer ***@***.***> schrieb am Sa. 27. Nov. 2021 um
08:55:

**Comment by flowerdealer** [comment]
Yes, I did exactly that, it doesn't work. Hdr is left on. It works only for
turning on for me. I'm on Windows 11 if that makes any difference, but my
modified version still works the same way.

**Comment by Codectory** [comment]
Is every monitor hdr capable?

flowerdealer ***@***.***> schrieb am Sa. 27. Nov. 2021 um
09:06:

> Yes, I did exactly that, it doesn't work. Hdr is left on. It works only for
> turning on for me. I'm on Windows 11 if that makes any difference, but my
> modified version still works the same way.
>

**Comment by flowerdealer** [comment]
Single hdr TV.
