### ISSUE TITLE
Add support for changing refresh rate and color depth with HDR

### ISSUE THREAD

**Issue by AbbieDoobie** [Codectory/AutoHDR#23]
Some monitors do not support 10-bit color depth at their highest refresh rate. Can settings be added for HDR and non-HDR refresh rate and color depth?

For example, my monitor supports 8-bit color depth at 160hz, or 10-bit color depth at 120hz. So I would set the following:

HDR: 120hz, 10-bit.
non-HDR: 160hz, 8-bit.

**Comment by ValZapod** [comment]
Yeah, 24 fps 12 bit RGB here on windows 11.

**Comment by Codectory** [comment]
At least, you can change the refresh rate. Didn't found a way for the color depth yet.

**Comment by Codectory** [comment]
So, I can read out bits per pixel, but I've tried everything. I haven't found any way to change it.

**Comment by Codectory** [comment]
@AbbieDoobie I hope you have a Nvidia graphics card (see 1.8,1)
