### ISSUE TITLE
AutoHDR changes resolution?

### ISSUE THREAD

**Issue by jamie9090** [Codectory/AutoHDR#24]
Fantastic app!

My main use case is with Moonlight (nVidia Gamestream).

I'm using this in conjuction with Gamestream Launcher (https://github.com/cgarst/gamestream_launchpad).

This app changes the resolution of your computer during a gamestream session.

For some reason, AutoHDR is changing my resolution back to my default when I enable HDR.

Anyone have experience with this situation?

I'm using a Samsung Odyssey G9 monitor, if that helps.

**Comment by Codectory** [comment]
You can do this with profiles now.
