### ISSUE TITLE
netflix windows 10 app

### ISSUE THREAD

**Issue by mananong** [Codectory/AutoHDR#26]
hi there, would it be possible to add the netflix windows 10 app on the app?

**Comment by Codectory** [comment]
The Netfix app is a web app and it doesn‘t have its own executables. I
haven‘t found a way to monitor these type of apps yet.

mananong ***@***.***> schrieb am Fr. 9. Juli 2021 um 23:48:

**Comment by mananong** [comment]
yeah figured as much.. hopefully maybe we could set a hotkey combination for toggling HDR?

**Comment by Codectory** [comment]
In the works, but I dont have much time these days.

mananong ***@***.***> schrieb am Fr. 9. Juli 2021 um 23:54:

**Comment by ValZapod** [comment]
> web app and it doesn‘t have its own executables. I haven‘t found a way to monitor these type of apps yet.

This is not talking about Edge netflix. This is appx.

**Comment by Codectory** [comment]
So where is the executable?

**Comment by ValZapod** [comment]
> where is the executable?

In C:\Progtam Files\WindowsApps

**Comment by Codectory** [comment]
Exactly please, which executable has to be monitored?

**Comment by ValZapod** [comment]
C:\Windows\System32\WWAHost.exe is actually used that is using C:\Program Files\WindowsApps\4DF9E0F8.Netflix_6.97.752.0_x64__mcm4njqhnhss8\microsoft.system.package.metadata\Autogen\JSByteCodeCache_64

**Comment by Codectory** [comment]
Thats to point. When you open netflix or any other app which is using this technology, WWAHost.exe gets started. So how should I know if netflix is running? Didn't found a way for this,.

**Comment by ValZapod** [comment]
Processhacker will show the actual command line that mentioned netflix.

**Comment by Codectory** [comment]
Let's see if I can get this information

**Comment by Codectory** [comment]
Got it! Check the new release 1.7.13
