### ISSUE TITLE
error pop up on pc restart, clicking X closes auto hdr

### ISSUE THREAD

**Issue by mananong** [Codectory/AutoHDR#27]
hi would like to report 2 issues (unrelated to each other)

1. if auto-hdr is running in the tray (withou auto hdr activated, just in the background) if i click on windows 10 restart, an error prompt pops up (i have to click OK in order for restart to proceed otherwise it will just be stuck there)

2. even when  close to tray is checked, when i close auto hdr window it quits app

**Comment by Codectory** [comment]
Could you show me a screenshot of the config file and the popup?

**Comment by mananong** [comment]
Hi here's some photos sorry i dont know how to open config files

http://imgur.com/a/bvhscKH

**Comment by rb2k5** [comment]
I've been seeing this since the last release too.

![AutoHDR exe config](https://user-images.githubusercontent.com/80460614/126014182-80ce9636-d1e2-469f-ab88-2ffdc4bd48e3.png)

**Comment by Codectory** [comment]
Could you post the log file when this has happened please?

**Comment by CZonin** [comment]
Been having the same 2 issues here for awhile.

![20210716_100227](https://user-images.githubusercontent.com/67965669/127739907-98064c4e-230a-41c7-a71b-caad82e0696f.jpg)

**Comment by rb2k5** [comment]
A wee update on this. I had to reinstall Windows 10 recently, to accommodate UEFI booting in preparation for Windows 11. Interestingly, the AutoHDR restarting issue is no longer present. Thinking it may have been a cash with another running app, although I couldn't say which one. As I continue re-installing stuff, I'll keep an eye on AutoHDR to try to identify which app is causing the crash. Looks like its not AutoHDR at fault, but some other process.
Hope this helps.

**Comment by Codectory** [comment]
Great to hear, I will close this issue for now
