### ISSUE TITLE
Not possible to add applications

### ISSUE THREAD

**Issue by Peronia** [Codectory/AutoHDR#33]
Hi,

with the 1.7 Update, its not possible to add applications, the "OK" button go away.

Before ("OK" is visible):
![grafik](https://user-images.githubusercontent.com/25049991/143184452-fcf0a8ae-bf24-4be8-b1dd-703f38e594b5.png)

After I set an application:
![grafik](https://user-images.githubusercontent.com/25049991/143184363-189e9af4-1afb-4e0b-9bd7-81d51aa6f700.png)

**Comment by Codectory** [comment]
Looks like the OK button has been moved out of the display rectangle. Will fix this soon.
