### ISSUE TITLE
Add application dialog - OK box disappears after choosing app.

### ISSUE THREAD

**Issue by rb2k5** [Codectory/AutoHDR#36]
{Sorry - Duplicate of #33}

AutoHDR 1.7.0
When using Add application dialog, the OK box disappears after choosing the application to add.
Maximizing the window doesn't bring it back.

![image](https://user-images.githubusercontent.com/80460614/143214161-c3a69e50-25c2-439f-adc9-6269544ccdad.png)

**Comment by Codectory** [comment]
see #33
