### ISSUE TITLE
1.7.2  Settings handling broken

### ISSUE THREAD

**Issue by res2k** [Codectory/AutoHDR#39]
Version 1.7.2 can't read it's own UserSettings.xml file if a profile is added that contains an application action:
The file is written on exit, but on the next start, the settings file is copied to a backup and all the settings are lost.

Adding an application or adding a profile without actions works.

(Side note: The 1.7.0, 1.7.1, and 1.7.2 tags all point to the same commit. That... does not make sense.
Either something changed, then there should be new commits, or nothing changed, then a tag is superfluous.
Or something changed, but outside revision control - this is not good.)

**Comment by Codectory** [comment]
oh, forgot to commit.  You are right. I am using datacontracts for the first time. I think I made some mistakes there. Will look into this asap.

**Comment by Codectory** [comment]
Should be fixed in 1.7.3
