### ISSUE TITLE
German support are broken

### ISSUE THREAD

**Issue by Peronia** [Codectory/AutoHDR#41]
In v. 1.7.5 the german translation isn't loaded (before it get loaded automatic, don't find any place to do it manually).

And btw: The readme here on github references to the events, they are not longer exists.

**Comment by Codectory** [comment]
Will fix that. Which events do you mean?

**Comment by Peronia** [comment]
I mean this one:
![grafik](https://user-images.githubusercontent.com/25049991/144662801-4ab73039-b263-4dca-9355-de6cb8a9b57a.png)

**Comment by Codectory** [comment]
I don’t get it. What’s wrong with the events?

Peronia ***@***.***> schrieb am Fr. 3. Dez. 2021 um 20:38:

**Comment by Peronia** [comment]
I think you disabled this with 1.7.3:
> Administrative rights were necessary for event logging (disabled for now)
And I can't see it in my program.

**Comment by Codectory** [comment]
No I didn’t. I disabled parts of a logging feature, not application events.

Peronia ***@***.***> schrieb am Sa. 4. Dez. 2021 um 02:58:

**Comment by Peronia** [comment]
Ah sorry, but it has gone in my version so I thought it was removed.
