### ISSUE TITLE
Upgrading from 1.7.1 to 1.7.5 wiped all settings

### ISSUE THREAD

**Issue by noblesigma** [Codectory/AutoHDR#43]
Hey there,

Been using this app forever. Got really excited that you're back in action.

With this latest change though, although it might be intentional, but just so you know, I lost all profiles & app settings. Will probably sit tight until this is worked out since that was a few hours of time.

Thanks

**Comment by Codectory** [comment]
Sorry fot that. Didn't find a way to import them into the "new" settings file, as the old one was really buggy.
