### ISSUE TITLE
Can't Create Settings File in Program Files

### ISSUE THREAD

**Issue by 545427** [Codectory/AutoHDR#44]
I don't know a ton about windows file structure, but I noticed an issue with the app. None of my settings or profiles were saving when I exited and restarted the app. When I checked the folder (which was located in my Program File folder on my drive) I noticed that there was no settings file. I moved the application to my desktop, ran it again, and instantly a new UserSettings.json file was created. 

Now, even upon moving the folder back into Program Files, settings and applications save between restarts.

From my limited knowledge, the problem seems to be that because the program does not have admin perms, it is unable to create the settings file when located in Program Files (which seems to have some extra protections). However, it can edit the file if it already exists.

To me, the easy solution seems to be to already have a settings file created with the download, bypassing this issue.

**Comment by Codectory** [comment]
Just change the security settings of the folder you want Auto HDR to be and
give non-admin users write access.

Tevin Hendess ***@***.***> schrieb am Fr. 3. Dez. 2021 um
03:50:

**Comment by 545427** [comment]
Yep, that was it. I just had to give the default user write perms. Thank you for your help!
