### ISSUE TITLE
Doesn't work with most games I've tried

### ISSUE THREAD

**Issue by Globespy** [Codectory/AutoHDR#47]
Tried with: 
Hunt: Showdown - get an error from easyanticheat.
The Witcher 3 - game doesn't even start when AutoHDR is open
Astroneer - game doesn't start when AutoHDR is open

Seems this might only be good for older games that don't have any kind of online multiplayer aspect?
Great idea, but I guess not good enough to outsmart game anti-cheat etc.

**Comment by Codectory** [comment]
This has nothing to do with anti-cheat. Witchter 3, Forza 5, AoE 4, Assassins creed Odyssey & Valhalla... all games are working perfectly for me.

**Comment by Globespy** [comment]
That's odd, maybe I don't have it setup properly?

**Comment by Globespy** [comment]
Figured it out - my mistake.
Thanks for the app :)
