### ISSUE TITLE
Add Check now function for updates

### ISSUE THREAD

**Issue by RavenMacDaddy** [Codectory/AutoHDR#48]
Is it possible to add a Check now function to the updates of the app? For example by a clickable text next to the checkbox option to check on startup.

**Comment by Codectory** [comment]
You can click on the blue Info text in the status bar to check if an update
is available. You can also click on „Buy me a beer“ 😉

RavenMacDaddy ***@***.***> schrieb am Fr. 3. Dez. 2021 um
12:18:

**Comment by RavenMacDaddy** [comment]
Good points. 

Would you consider however to change maybe text or placement (or both) considering it was something that wasn't realized intuitively.

Also, really enjoying your software so far, it's of great use combined with Windows 11's AutoHDR feature.

**Comment by RavenMacDaddy** [comment]
Very much improved visibility of buttons overall in the referenced version and those that follow, closing.
