### ISSUE TITLE
Switching to HDR according to profile settings seems broken

### ISSUE THREAD

**Issue by RavenMacDaddy** [Codectory/AutoHDR#50]
Running the latest version at the time of writing; 1.7.8, the profile that I'm using seems to be non-functional;

![image](https://user-images.githubusercontent.com/67732686/144629797-6defed23-5249-474c-be82-7f130650a5c6.png)

I think it worked in 1.7.5 or 1.7.6, but now that I start apps that I've used previously with the expected switching behavior happening, nothing actually happens anymore.

The screen just flashes, but HDR is never enabled or disabled.

And to be clear, I'm not referencing actually changing any profiles or assigned profiles to my apps, the same settings just don't function as expected.

Could it be related to just overwriting the old version with the new one, like the config file that's included with every version?

**Comment by Codectory** [comment]
Can you send me you log file please?

**Comment by RavenMacDaddy** [comment]
![image](https://user-images.githubusercontent.com/67732686/144638767-3f6f5c8f-085f-4a12-862f-f4a53d7bd716.png)

This is at the end.

Can't seem to find a way to export the whole log, is there?

**Comment by Codectory** [comment]
Please create a log file and send me the file. I cannot see the important infos in the screenshot and I cannot reproduce this

**Comment by RavenMacDaddy** [comment]
That's what I'm puzzled about, how do I create a log file?

I can't seem to find this info in the Readme here on the project, or any existing log files in AppData or the Documents folder, but I might be missing something.

**Comment by Codectory** [comment]
In the settings, there is a toggle.

**Comment by RavenMacDaddy** [comment]
My bad, missing a lot today, I'll get right to it.

**Comment by RavenMacDaddy** [comment]
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7653961/AutoHDR.log)

Same thing occurs. The log still says that it enables HDR for all displays, but it doesn't - however - if I actually specify a monitor, it does work.

So seemingly the All displays option is not functioning.

**Comment by Codectory** [comment]
Maybe the settings doesn’t work for all monitors?

RavenMacDaddy ***@***.***> schrieb am Sa. 4. Dez. 2021 um
14:06:

**Comment by RavenMacDaddy** [comment]
Nothing's impossible, but that just makes it very ironic, don't you think?

How do we solve this? What data do you need?

**Comment by Codectory** [comment]
Try to set the settings manually for each monitor

RavenMacDaddy ***@***.***> schrieb am Sa. 4. Dez. 2021 um
14:16:

**Comment by RavenMacDaddy** [comment]
Sure, like described previously that works.

Hopefully the function for All displays is fixed in a future version - tell me if you want data to troubleshoot it.
