### ISSUE TITLE
Monitor tab, displays add/remove don't change, stats are not correct on all.

### ISSUE THREAD

**Issue by tarvcode** [Codectory/AutoHDR#58]
1. Displays don't refresh when new monitor is added/removed.  I have a 3rd monitor that is off most of the time, but if it's on when the app starts, DISPLAY3 never goes away.  Same is true if it's off an turned on, never appears.

2. Inconsistency with bringing in display stats on the monitors tab.  At one point it was showing all three of my monitors with the same resolution/refresh as 1.  Now it's getting 1 and 3 correct, but 2 is only capable of 75hz refresh.  Also don't know if it matters, but only 1 is capable of HDR.

![image](https://user-images.githubusercontent.com/16649815/144754640-9fb04f23-587c-44e6-aea8-9377e8704fa0.png)

Love the app!

**Comment by Codectory** [comment]
That’s correct. I don’t update monitor data at the moment. Only ok start up
and when you change the settings through AutoHDR.

Tarv ***@***.***> schrieb am So. 5. Dez. 2021 um 17:24:

**Comment by Codectory** [comment]
Could you check the behaviour in 1.7.14?

**Comment by tarvcode** [comment]
tried 1.7.14 then 1.7.16.  application crashes when I turn the third monitor on or off.

will also note, this value is wrong (should be 75hz) but I do notice it flickering once in a while showing 75 for 1/10 of a second.

![image](https://user-images.githubusercontent.com/16649815/145684895-469e15a3-0158-4c64-9968-1102f02c2c6d.png)

**Comment by Codectory** [comment]
Ok, I have to get another monitor for tests. All multi monitor things are
just „code and pray“ ;-)

Tarv ***@***.***> schrieb am Sa. 11. Dez. 2021 um 17:54:

**Comment by tarvcode** [comment]
FYI just rolled back through some past versions.  Application crash on monitor on/off starts with 1.7.11.  1.7.10 works fine.

Also noticed that 1.7.10 remembers the window size of the application if I change it, but after that 1.7.11 onward the application just opens with the default window size.

**Comment by Codectory** [comment]
Fixed in 1.7.17
