### ISSUE TITLE
The refresh rate option doesn't work

### ISSUE THREAD

**Issue by RavenMacDaddy** [Codectory/AutoHDR#59]
Was attempting to use this option to switch my high refresh rate monitor from 280Hz to 144Hz to enable 10 bit color depth, though it doesn't work, and it only says "0Hz" when you enable the function in the profile settings.

**Comment by Codectory** [comment]
Which frequency can you see in the monitors tab?

**Comment by RavenMacDaddy** [comment]
Nothing specific it seems. 

Free to specify. 

What shows up as the initial value for the option seems to be based on what's currently active on the monitor when entering the menu, though.

**Comment by Codectory** [comment]
So, its working now?

**Comment by RavenMacDaddy** [comment]
No it's always been like this; the values seem correct except when I actually set the option for an action in the profile.

It just says 0 when you check the action value and nothing happens when running a game with the profile selected.

**Comment by Codectory** [comment]
I don't get it. Which refresh rate do you want to set? Please send me you UserSettings.json file

**Comment by RavenMacDaddy** [comment]
[UserSettings.zip](https://github.com/Codectory/AutoHDR/files/7694674/UserSettings.zip)

144Hz is set in the profile.

![image](https://user-images.githubusercontent.com/67732686/145622309-b101ce14-42de-4cf6-a441-ffccd0592c52.png)

Using it for Call of Duty: Black ops 2 fore example.

![image](https://user-images.githubusercontent.com/67732686/145622387-38acedbd-349e-4d7b-8875-f3cdbb2f9ad0.png)

... but something is not working, and the resulting refresh rate option says 0.

**Comment by Codectory** [comment]
Fixed in 1.7.14
