### ISSUE TITLE
Selectable display number stays at the highest device number it's been on so far even after restart of the app and JSON editing

### ISSUE THREAD

**Issue by RavenMacDaddy** [Codectory/AutoHDR#60]
So, Windows 11 is still weird and probably will be for some time.

This makes my TV just rise in terms of which device number it gets, which is currently "6".

In the case of AutoHDR, that was fine as I was experimenting with the monitor, making profiles for it.

However, once I was done, I noticed that while I tested editing the profiles when I was on my main monitor again, Display 1, that in the drop-down menu, it will only show Display 6 - and it stays that way after trying to troubleshoot the issue by restarting the app, updating it to the latest at the time of writing; 1.7.11, and editing the JSON back to Display 1.

No matter what I've done so far, the app will only show Display 6 as selectable right now when editing profiles.

![image](https://user-images.githubusercontent.com/67732686/144905069-d4cecda6-de73-4f7d-a9ca-665eb3e7cb15.png)

EDIT: ... and according to the Monitors tab, this monitor is now Display 6.

![image](https://user-images.githubusercontent.com/67732686/144908581-2c300ab6-293a-4e5c-ba96-e628760bc9ea.png)

Then what the *** is my TV now!?

The answer is the number crash, cause the app just died when I switched to my TV, and there it says Display 6.

Now switching back to the main monitor, and it dies again.

Starting the app again, and it still says display 6, so basically the non-direct theory checks out; with a single display active, the app will just identify it by the highest device number so far.

Some more interesting things to note:

- The corresponding specs like refresh rate checks out depending on which monitor is currently active, as can be seen in the screenshot above; 1080p, 280Hz compared to 4K, 60Hz for the TV.
- Even if I didn't edit the profile for my main monitor from Display 1 to Display 6, it still works.

**Comment by Codectory** [comment]
Please attach a logfile. I am using only one monitor, so thats one thing I cannot completely test.

**Comment by RavenMacDaddy** [comment]
Can't reproduce, closing for now.
