### ISSUE TITLE
AutoHDR v1.7.16 does not start / slow start / invisible

### ISSUE THREAD

**Issue by GODzillaGSPB** [Codectory/AutoHDR#68]
**Describe the bug**
When starting AudoHDR 1.7.16 it does not appear. It runs in the background, but no programm window appears, nor a tray icon. Sometimes, after several tries, it eventually does appear.

My best guess at what really happens: I think it starts just fine, even at first try, but it takes several minutes for the tray icon to appear (I've set it up to start minimized). I'm unsure as to why this happens. Was using 1.6.2 prior, started right away, always. Thinking of going back to that old version even...

**To Reproduce**
Installed 1.7.16, made sure to completely erase all files from the previous version. Starting it once, twice, a third time. Eventually it appears. Between tries I end the programm using Task Manager.

Curiously, after it started properly once, I can exit the programm, start it up again and it appears normal, without the delay. It's only that first startup it seems...

**Expected behavior**
It should always start reliable and fast since it's a small programm I guess.

**Files**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Version 21H1 Build 19043.1348
 - Version 1.7.16 from Dezember 16th. (but I actually experienced the same behavior with 1.7.15)

**Hardware (please complete the following information):**
 - Monitors: two monitors, but only one active at a time
 - Graphics card: RTX 3090
- Graphics card driver: 497.09

**Additional context**
-

**Comment by GODzillaGSPB** [comment]
![AutoHDR_1 7 16_Startup_log](https://user-images.githubusercontent.com/95964096/145676315-26f51180-5808-4f15-87d1-6f3ebd8b9752.JPG)

**Comment by GODzillaGSPB** [comment]
Added the first startup log above. As you can see it takes the programm just shy of two minutes for the first start after a system reboot. When I start it a second time it performs the exact same steps in just about 4 seconds.

Well I guess for now I can live with that and will stay with that version. There have been numerous bugfixes since 1.6.2 and now that I know of the 2 minute delay for first time start it's okay. ;) Still I guess this is not expected behavior, or is it?

**Comment by Codectory** [comment]
This could be related to anti virus software. On the next update, open the
task manager first and look for the process with the highest cpu
utilization.

GODzillaGSPB ***@***.***> schrieb am Sa. 11. Dez. 2021 um
13:22:

**Comment by GODzillaGSPB** [comment]
I only use what comes with Windows 10. No dedicated AV software is installed. I also just checked advanced settings for the Windows firewall to see if AutoHDR is blocked. Not in the list, doesn't come as a surprise. I don't have "check for updates on startup" enabled.

**Comment by GODzillaGSPB** [comment]
I did what you suggest and monitored the task manager, order by CPU usage and one process was definitely sticking out during the AutoHDR startup, but I have no idea how this could possible be connected to your programm. See screenshot below. Sorry it's in German, but I guess you could check out the service in your services tab.

**Comment by GODzillaGSPB** [comment]
![AutoHDR_1 7 16_Startup_Task](https://user-images.githubusercontent.com/95964096/145679558-8e638a7d-4a19-409c-ab29-b9ff733447b9.JPG)

**Comment by Codectory** [comment]
There is one action to change the audio devices. I am using some „buggy“
library for this. Will for an alternative. I think this is causing the
delay. BTW, I am from Germany ;-)

GODzillaGSPB ***@***.***> schrieb am Sa. 11. Dez. 2021 um
15:08:

**Comment by GODzillaGSPB** [comment]
Hey, that's cool. But I guess for the sake of accessability we should probably stick to english, others read these forums, too. :)

And thanks for looking into this, really appreciate your work. Prior to discovering your tool, using HDR games in Windows has always been a hassle. I almost couldn't believe it when I found it and it worked so easily. ^^ Why there isn't a simple switch or even an automatic setting in Windows for HDR content is beyond me.
