### ISSUE TITLE
A HDR STOP Function is missing in the profile settings

### ISSUE THREAD

**Issue by Grillhuber** [Codectory/AutoHDR#70]
A HDR STOP Function is missing in the profile settings. It gives a Option to enable HDR by application start, but option to disable HDR by stop the application is missed.

**Comment by Codectory** [comment]
You can do this in the application closed event.

Grillhuber ***@***.***> schrieb am Do. 16. Dez. 2021 um 12:13:

**Comment by RavenMacDaddy** [comment]
As @Codectory is saying, the next step is when an app is stopped, where you just keep HDR state as unticked = disabled.
