### ISSUE TITLE
v1.8.1+: Refresh rate switching is broken again

### ISSUE THREAD

**Issue by RavenMacDaddy** [Codectory/AutoHDR#74]
**Describe the bug**
This was a bug previously where the app wouldn't switch the refresh rate as specified.

It was addressed and is now back, but the app doesn't say "0 Hz" as it did previously when it wasn't working and is switching to HDR as expected, so it's not seemingly that it's confused what screen to modify.

**To Reproduce**
1. Specify a specific refresh rate in your profile, e.g. 144 Hz like in my case to make 10 bit color depth available.
2. Assign this profile to a suitable title, e.g. something demanding or alternatively something that's FPS capped to something like 60 anyway.
3. Start the title that should switch the monitor's refresh rate as specified.

**Expected behavior**
As I start a title which has my corresponding profile assigned, it should both enable HDR, as well switch to the specified refresh rate.

**Files**

![image](https://user-images.githubusercontent.com/67732686/146914501-fa71a240-bd09-4bfd-8f16-4c49cbdb84a0.png)

![image](https://user-images.githubusercontent.com/67732686/146914535-bede63a8-97ed-4ad6-9c8c-3595e7f7f753.png)

[Logs.zip](https://github.com/Codectory/AutoHDR/files/7751830/Logs.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 - 22000.376
 - Version 1.8.1 at the time of writing

**Hardware (please complete the following information):**
 - Monitors: ASUS TUF Gaming VG279QM
 - Graphics card: MSI GTX 1080
- Graphics card driver: 497.09

**Comment by Codectory** [comment]
Fixed in 1.8.2
