### ISSUE TITLE
Profile's setting not being saved

### ISSUE THREAD

**Issue by jeezany** [Codectory/AutoHDR#86]
**Describe the bug**
First of all, I have 4 monitors.
I have created a new profile called "HDR". I created two application start action and one application closed action.
The two application start action each enable HDR on one display
The one application closed action disable HDR in all displays.
When I close the application or shutdown/restart my system it will select all the monitors for enabling HDR

**To Reproduce**
1. change the setting like you want for each display
2. restart the application/system
3. it will reverse to select all

**Expected behavior**
Keeping only the displays that I selected

**Files**
[AutoHDR.exe.zip](https://github.com/Codectory/AutoHDR/files/7808951/AutoHDR.exe.zip)

Add logfile, UserSettings.json and, if applicable, screenshots to help explain your problem.
Done

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version Version 21H2 (OS Build 22000.376)

**Hardware (please complete the following information):**
 - Monitors: TUF VG27AQ, [HDR]
 - Samsung CHG27, [HDR]
 - ViewSonic VS16263, 
 - LG CX [HDR]
 - Graphics card: MSI 3080
- Graphics card driver: 497.29

**Additional context**

**Comment by Codectory** [comment]
I don't really understand the problem. You want enable HDR on just one monitor, but HDR gets enabled for all monitors?

**Comment by jeezany** [comment]
When I configure the profile to enable in one monitor it will work fine. 
if I restarted the application (AutoHDR) or restarted my PC, the profile will be configured to enable HDR in all monitors.

**Comment by DfrostX** [comment]
I`m seeing something similar. In the monitor tab, ticking off "automated HDR mode" on one monitor (I have 2) will work fine until I reboot. Then both monitor will have "automated HDR mode" ticked again.
