### ISSUE TITLE
Action shortcuts display selection not being saved after restart

### ISSUE THREAD

**Issue by jeezany** [Codectory/AutoHDR#89]
**Describe the bug**

First of all, I have 4 monitors.
In the Settings tab. When create an action that modify HDR from No to Yes or vice versa and selecting a single display for the change it will work fine. If I restarted The application "AutoHDR" or restarted my PC the action will select all displays.

**To Reproduce**

1. change the setting like you want for each display
2. restart the application/system
3. it will reverse to select all

**Expected behavior**
Keeping only the displays that I selected

**Files**
[AutoHDR.zip](https://github.com/Codectory/AutoHDR/files/7833124/AutoHDR.zip)

**Desktop (please complete the following information):**
- OS: Win 11
- Version Version 21H2 (OS Build 22000.376)

**Hardware (please complete the following information):**
- Monitors: TUF VG27AQ, [HDR]
- Samsung CHG27, [HDR]
- ViewSonic VS16263,
- LG CX [HDR]
- Graphics card: MSI 3080
- Graphics card driver: 497.29

**Additional context**

**Comment by Codectory** [comment]
Do you use the current version? This should be fixed in 1.9.3

jeezany ***@***.***> schrieb am Sa. 8. Jan. 2022 um 12:30:

**Comment by jeezany** [comment]
Yes Version 1.9.3

Attached the setting before and after restarting the application "AutoHDR"

![Screenshot 2022-01-08 191932](https://user-images.githubusercontent.com/35895669/148651625-6ca8fa39-ccd6-48cf-9175-34fa0d5d050a.png)

![Screenshot 2022-01-08 192010](https://user-images.githubusercontent.com/35895669/148651623-c33fad53-fab5-474b-8799-a0931191d7cb.png)

**Comment by Codectory** [comment]
Alright, I will check this

jeezany ***@***.***> schrieb am Sa. 8. Jan. 2022 um 17:21:

**Comment by Codectory** [comment]
Fixed
