### ISSUE TITLE
Won't save profiles. (Ver 1.94)

### ISSUE THREAD

**Issue by Finbester** [Codectory/AutoHDR#92]
Hi! AutoHDR won't save profiles after "Exit application" or restart. That leads to HDR being on on my other display, since putting Display 3 won't save. So it goes back to all displays.

**Comment by Codectory** [comment]
It saves no settings or no display settings?

Finbester ***@***.***> schrieb am Mo. 10. Jan. 2022 um 20:55:

**Comment by Finbester** [comment]
The dispay settings won't save.

**Comment by Codectory** [comment]
Fixed
